version: '3.5'

services:
  smallfish-web:
    image: nginx
    ports:
      - 80:80
      - 443:443
    container_name: 'smallfish-web_dev'
    restart: unless-stopped
    volumes:
      - ../dist:/usr/share/nginx/html:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  dist: